name:  Release to PyPI

on:
  push:
    tags:
       - '*'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies for testing
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build
          pip install -e .
        # pip install PySide6
        # pip install .[test]
      #- name: Test core with pytest
      #  run: |
      #    pytest spikeinterface-gui
      - name: Package and Upload
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m build --sdist --wheel
          twine upload dist/*
